name: CI/CD Angular + Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias Angular
        working-directory: ./frontend
        run: npm install

      - name: Build Angular
        working-directory: ./frontend
        run: npm run build -- --output-path=dist

      - name: Configurar Java y Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot
        working-directory: ./backend
        run: mvn clean package -DskipTests

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build + Push imagen frontend
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-training:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-training:latest

      - name: Build + Push imagen backend
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-training:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-training:latest

      # (opcional) Desplegar en Kubernetes si usas un self-hosted runner
